import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const BlockchainInsight: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cardano Blockchain Insights - Cardano Fans</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Cardano Blockchain Insights</h1>
      </main>
    </div>
  )
}

export default BlockchainInsight
